### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [monsieurbadia/d2k.js#1]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by monsieurbadia** [comment]
Man that's a f*cking 👍 idea ! I forgot TypeScripters. If you still want to write a TypeScript type declaration, it interest me.

**Comment by geopic** [comment]
Good stuff @monsieurbadia, I'll start on it now.

**Comment by geopic** [comment]
So this library is complex, more complex than I first thought. :eyes: Sorry for not being able to do what I said I could do. Maybe somebody else more adept at TypeScript can write a type declaration file.

**Comment by monsieurbadia** [comment]
Thank you for your response and for taking your time to watch the project. There are areas for improvement in my application. Maybe I'll take some time this weekend to rethink it all in a simpler way. I close the issue.
